# Generated by Django 2.2.7 on 2019-12-13 17:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='images/users/noavatar.png', upload_to='images/users', verbose_name='Изображение')),
                ('balacne', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
                ('theme', models.CharField(choices=[('l', 'Светлый'), ('d', 'Темный')], default='l', help_text='Тема страницы, для пользователья.', max_length=1, verbose_name='Тема')),
                ('readed_books', models.ManyToManyField(blank=True, to='catalog.Book', verbose_name='Книги, отмеченные как - "Прочитано"')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
