# Generated by Django 2.2.7 on 2020-02-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_chaptercomment_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='chaptercomment',
            options={'verbose_name': 'Комментарий к главе', 'verbose_name_plural': 'Комментарии к главам'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Резенция', 'verbose_name_plural': 'Резенции'},
        ),
    ]
